services:
  db:
    image: postgres
    profiles: [backend, postgres-full, postgres]
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
  pgadmin: 
    image: dpage/pgadmin4
    profiles: [backend, postgres-full, pgadmin]
    restart: always
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
  redis: 
    image: redis/redis-stack:latest
    profiles: [backend, redis]
    ports:
      - ${REDIS_PORT}:6379
      - ${REDIS_UI_PORT}:8001
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  rabbit:
    image: rabbitmq:management
    profiles: [backend, rabbitmq]
    restart: always
    ports: 
      - ${RABBIT_MQ_PORT}:5672
      - ${RABBIT_MQ_UI_PORT}:15672
  tunes:
    build:
      dockerfile: Dockerfile
    profiles: [backend, tunes]
    ports:
      - ${PORT}:${PORT}
    depends_on: 
      db: 
        condition: service_healthy
      redis:
        condition: service_healthy



