include .env

goose-up:
	GOOSE_DRIVER=postgres GOOSE_DBSTRING=$(GOOSE_DBSTRING) GOOSE_MIGRATION_DIR=$(GOOSE_DIR) goose up
goose-reset:
	GOOSE_DRIVER=postgres GOOSE_DBSTRING=$(GOOSE_DBSTRING) GOOSE_MIGRATION_DIR=$(GOOSE_DIR) goose reset


