definitions:
  responses.PaginationResponse-array_responses_User-string:
    properties:
      dataResponse:
        items:
          $ref: '#/definitions/responses.User'
        type: array
      paginationKey:
        type: string
    type: object
  responses.Role:
    enum:
    - BASIC
    - MODERATOR
    - ADMIN
    type: string
    x-enum-varnames:
    - BASIC_USER
    - MODERATOR
    - ADMIN
  responses.User:
    properties:
      bio:
        type: string
      role:
        $ref: '#/definitions/responses.Role'
      spotifyID:
        type: string
      username:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: jack.a.gitter@gmail.com
    name: Jack Gitter
  description: The backend REST API for Tunes
  title: Tunes backend API
  version: "1.0"
paths:
  /users/{spotifyID}:
    get:
      consumes:
      - application/json
      description: Gets a tunes user by their spotifyID
      parameters:
      - description: User Spotify ID
        in: path
        name: spotifyID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.User'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - Bearer: []
      summary: Gets a tunes user by their spotify ID
      tags:
      - Users
  /users/{spotifyID}/followers/:
    get:
      consumes:
      - application/json
      description: Gets a users followers by their spotify ID
      parameters:
      - description: User spotify ID
        in: path
        name: spotifyID
        required: true
        type: string
      - description: Pagination Key for follow up responses. This key is a spotify
          ID
        in: query
        name: spotifyID
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.PaginationResponse-array_responses_User-string'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - Bearer: []
      summary: Gets a users followers by their spotify ID
      tags:
      - Users
  /users/current:
    get:
      consumes:
      - application/json
      description: Retrieves the current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.User'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - Bearer: []
      summary: Retreives the current user
      tags:
      - Users
  /users/current/follow/{otherUserSpotifyID}:
    post:
      consumes:
      - application/json
      description: Follows a user for the current user
      parameters:
      - description: Spotify ID of other user to follow
        in: path
        name: spotifyID
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - Bearer: []
      summary: Follows a user for the current user
      tags:
      - Users
  /users/current/followers/:
    get:
      consumes:
      - application/json
      description: Gets the current users followers
      parameters:
      - description: Pagination Key for follow up responses. This key is a spotify
          ID
        in: query
        name: spotifyID
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.PaginationResponse-array_responses_User-string'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - Bearer: []
      summary: Gets the current users followers
      tags:
      - Users
  /users/current/unfollow/{otherUserSpotifyID}:
    post:
      consumes:
      - application/json
      description: Unfollowers a user for the currently signed in user
      parameters:
      - description: User spotify ID
        in: path
        name: spotifyID
        required: true
        type: string
      - description: User to unfollow spotify ID
        in: path
        name: otherUserSpotifyID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - Bearer: []
      summary: Unfollowers a user for the currently signed in user
      tags:
      - Users
securityDefinitions:
  Bearer:
    description: '"Authorization header value"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
